server:
  port: 8081

spring:
  application:
    name : customer-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true

customer:
  topic:
    name: customerTopic

order:
  topic:
    name: orderTopic

kafka:
  bootstrapAddress: boot-mjlfzxah.c1.kafka-serverless.ap-northeast-2.amazonaws.com:9098